apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-matricula
spec:
  replicas: 2  # Cambia según tus necesidades
  selector:
    matchLabels:
      app: sistema-matricula
  template:
    metadata:
      labels:
        app: sistema-matricula
    spec:
      containers:
      - name: sistema-matricula
        image: enriquemacias21/python-flask:latest  # Asegúrate de que este nombre sea correcto
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:admin123@postgres:5432/sistema_matricula
        ports:
        - containerPort: 5000  # Puerto en el que tu app escucha
---
apiVersion: v1
kind: Service
metadata:
  name: sistema-matricula
spec:
  type: LoadBalancer  # Cambia a LoadBalancer si es necesario
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: sistema-matricula