version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image:
      jalcivar13/app-python-flask
    ports:
      - "900:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:2511@db:5432/sistema_matricula
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2511
      POSTGRES_DB: sistema_matricula
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
